[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
board_build.f_cpu = 240000000
monitor_speed = 115200

lib_deps =
    m5stack/M5Unified @ ^0.2.4
    m5stack/M5GFX @ ^0.2.4
    bblanchon/ArduinoJson @ ^7.0.0
